apiVersion: apps/v1
kind: Deployment
metadata:
  name: absence-cep-consumer
  labels:
    app: absence-cep-consumer
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: absence-cep-consumer
  template:
    metadata:
      labels:
        app: absence-cep-consumer
    spec:
      containers:
        - name: absence-cep-consumer
          image: your-registry/absence-cep-consumer:latest  # Replace with actual image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
env:
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: my-app-secrets
        key: DB_USERNAME
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: my-app-secrets
        key: DB_PASSWORD
