apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-app-cron
  namespace: my-namespace
  labels:
    app: my-app
spec:
  schedule: "0 1 * * *"                  # Runs daily at 1:00 AM
  concurrencyPolicy: Forbid              # Don't allow overlapping runs
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2                    # ✅ Retry job up to 2 times if it fails
      template:
        metadata:
          labels:
            app: my-app
        spec:
          restartPolicy: OnFailure
          serviceAccountName: my-app-service-account
          containers:
            - name: my-app-container
              image: my-dockerhub-user/my-app:latest
              ports:
                - containerPort: 8080
              env:
                - name: APP_MODE
                  value: "production"
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: my-app-config
                      key: db_host
                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: my-app-secrets
                      key: secret_key
              volumeMounts:
                - name: app-storage
                  mountPath: /data
                - name: config-volume
                  mountPath: /app/config
                  readOnly: true
                - name: secret-mount
                  mountPath: /mnt/secret-bank
                  readOnly: true
                - name: absence-cep-consumer-pod-logs
                  mountPath: /applogs
                  readOnly: false
          volumes:
            - name: app-storage
              emptyDir: {}
            - name: config-volume
              configMap:
                name: my-app-config
            - name: secret-mount
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "event-consumer-secret-provider"
            - name: absence-cep-consumer-pod-logs
              hostPath:
                path: /app/logs
                type: DirectoryOrCreate
