apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: event-consumer-secret-provider
  namespace: my-namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"              # Not using Pod Identity
    clientId: "<your-managed-identity-client-id>"  # Client ID of the user-assigned identity
    keyvaultName: "<your-keyvault-name>"           # Azure Key Vault name
    objects: |
      array:
        - objectName: my-secret-key               # Name of secret in Key Vault
          objectType: secret                      # secret | key | certificate
          objectVersion: ""                       # optional (latest if omitted)
        - objectName: another-secret
          objectType: secret
  secretObjects:                                  # Optional: sync to native Kubernetes secret
    - secretName: my-app-secrets
      type: Opaque
      data:
        - objectName: my-secret-key
          key: secret_key
        - objectName: another-secret
          key: another_key
